# Read the Docs configuration file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

formats:
  - pdf
  - epub

python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - latexmk
    - ffmpeg
