version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - latexmk

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - epub
