codecov:
  require_ci_to_pass: true
  max_report_age: off
  notify:
    after_n_builds: 3
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
    changes: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  require_base: no
  branches: null
  flags: null

ignore:
  - "**/__pycache__"
  - "**/tests"
  - "**/examples"
  - "**/docs"
  - "**/.github"
  - "**/setup.py"
  - "**/versioneer.py"
  - "**/__init__.py"
  - "**/version.py"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
