name: Run tests and upload coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Python 3.11
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib pytest pytest-cov ipython pytest-xvfb
        pip install -e .
    
    - name: Run all tests with coverage
      run: |
        # Set non-interactive backend for matplotlib
        export MPLBACKEND=Agg
        # Run all tests with xvfb for display
        xvfb-run -a python -m pytest tests/ --cov=porcupy --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true